### ISSUE TITLE
FacebookSkraper grabs media, but no text from a shared post

### ISSUE THREAD

**Issue by IvanTrendafilov** [sokomishalov/skraper#146]
I am not sure if this is a bug or it is intended to be like that but, for example, [take this post](http://facebook.com/4346072205438814):

skraper returns this:

```
{
  "id" : "4346072205438814",
  "text" : "What a wonderful moment this morning at Waller Elementary. We LOVE our military kids and are grateful for their service and the service of their parents!",
  "publishedAt" : 1618250078,
  "rating" : 161,
  "commentsCount" : 2,
  "viewsCount" : 0,
  "media" : [ {
    "url" : "https://external.ficn4-1.fna.fbcdn.net/safe_image.php?d=AQGoUDzXwoNh4UmX&w=476&h=249&url=https%3A%2F%2Fwww.mypanhandle.com%2Fwp-content%2Fuploads%2Fsites%2F88%2F2021%2F04%2FSOTVO.00_00_19_21.Still001.jpg%3Fw%3D1280&cfs=1&upscale=1&fallback=news_d_placeholder_publisher&ccb=3-4&_nc_hash=AQGw4aGBDe67H8FP",
    "aspectRatio" : 1.9112903225806452
  } ]
}
```

The grabbed media is from the re-shared post, but there is no text - in this case that would be the partial url. There is also no way to tell if a post has media that they uploaded vs media from something that they re-shared.

**Comment by sokomishalov** [comment]
Hi, thanks for raising this issue!
Well, current behavior for extracting post text - it takes original post text, and if it's absent repost text.
I've made a [fix](https://github.com/sokomishalov/skraper/commit/08a76d691226041dce3a303c400247ce1edcb38c), which concatenate them with double line breaks but haven't merged it yet to the main branch because it's not an ideal solution from my perspective. Maybe it's enough as a temporary fix for now, but I think we should introduce an additional field, which will hold repost information. BTW I think it correlates to your issue (https://github.com/sokomishalov/skraper/issues/109).
I'm not sure about the content of that repost field, but I'm quite sure it's time to add it.
@IvanTrendafilov How do you think?

**Comment by IvanTrendafilov** [comment]
I think a separate repost field makes sense. In the Facebook API, they have that concept and they call it an "attachment". The attachment being any re-shared post (and I think even external articles). They have the following three fields: `attachment_title, attachment_description, attachment_url`. Now, I am not sure if these fields make sense for Skraper, but hopefully it is useful for context.
